show tables;
describe albums;
describe SocialMediaAccounts;
CREATE TABLE SocialMediaAccounts (ProfileName varchar (255), Mastodon boolean, Peertube boolean, PixelFed boolean);
DROP TABLE SocialMediaAccounts;
SHOW TABLES;
ALTER TABLE Albums ADD PRIMARY KEY (AlbumID);
ALTER TABLE genres ADD PRIMARY KEY (GenreID);
ALTER TABLE albums ADD CONSTRAINT fk_AlbumGenre FOREIGN KEY (GenreID) REFERENCES Genres(GenreID);
CREATE INDEX idx_artistsName ON Artists (StageName);
SHOW INDEX FROM Artists;
ALTER TABLE Albums MODIFY AlbumID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE Albums AUTO_INCREMENT=1000;
ALTER TABLE Albums ADD CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP;
DROP VIEW ArtistBDAY;
ALTER VIEW ArtistBDAY AS SELECT RealName, PhoneNumber, BirthDate FROM Artists;
CREATE VIEW artistBDAY AS SELECT RealName, PhoneNumber FROM Artists;
